priority(admission,todo).
priority(life,todo).
priority(dl,todo).
priority(apartment,todo).
priority(books,todo).
priority(capek,todo).
priority(dobry,todo).
priority(movies,todo).
priority(czeck_movies,todo).
priority(kuky,todo).
priority(kolja,todo).
priority(wild,todo).
priority(tax,todo).
priority(academics,todo).
priority(prilim,todo).
priority(quals,todo).
priority(cs582,done).
priority(cs321,done).
priority(cs581,todo).
priority(cs533,todo).
priority(cs507,todo).
priority(research,todo).
priority(ta,done).
priority(ta,todo).
priority(intern,todo).
priority(ihouse,todo).
priority(rent,todo).
priority(paper,todo).
priority(conra,todo).
priority(meeting,todo).
priority(spring:2012,normal).
