status(admission,todo).
status(life,todo).
status(dl,todo).
status(apartment,todo).
status(books,todo).
status(capek,todo).
status(dobry,todo).
status(movies,todo).
status(czeck_movies,todo).
status(kuky,todo).
status(kolja,todo).
status(wild,todo).
status(tax,todo).
status(academics,todo).
status(prilim,todo).
status(quals,todo).
status(cs582,done).
status(cs321,done).
status(cs581,todo).
status(cs533,todo).
status(cs507,todo).
status(research,todo).
status(ta,done).
status(ta,todo).
status(intern,todo).
status(ihouse,todo).
status(rent,todo).
status(paper,todo).
status(conra,todo).
status(meeting,todo).
status(spring:2012,todo).
