parent(academics,cs321).
parent(academics,cs507).
parent(academics,cs533).
parent(academics,cs581).
parent(academics,cs582).
parent(academics,intern).
parent(academics,prilim).
parent(academics,quals).
parent(academics,research).
parent(academics,ta).
parent(books,capek).
parent(books,dobry).
parent(czech_movies,wild).
parent(czeckmovies,kolja).
parent(czeckmovies,kuky).
parent(ihouse,rent).
parent(life,apartment).
parent(life,books).
parent(life,dl).
parent(life,ihouse).
parent(life,movies).
parent(life,tax).
parent(main,osu).
parent(movies,czeckmovies).
parent(osu,academics).
parent(osu,admission).
parent(osu,life).
parent(osu,spring).
parent(research,paper).
parent(ta,meeting).
parent(tax,conra).
