priority(osu,admission,todo).
priority(osu,life,todo).
priority(life,dl,todo).
priority(life,apartment,todo).
priority(life,books,todo).
priority(books,capek,todo).
priority(books,dobry,todo).
priority(life,movies,todo).
priority(movies,czeck_movies,todo).
priority(czech_movies,kuky,todo).
priority(czech_movies,kolja,todo).
priority(czech_movies,wild,todo).
priority(life,tax,todo).
priority(osu,academics,todo).
priority(academics,prilim,todo).
priority(academics,quals,todo).
priority(academics,cs582,done).
priority(academics,cs321,done).
priority(academics,cs581,todo).
priority(academics,cs533,todo).
priority(academics,cs507,todo).
priority(academics,research,todo).
priority(academics,ta,done).
priority(academics,ta,todo).
priority(academics,intern,todo).
priority(life,ihouse,todo).
priority(ihouse,rent,todo).
priority(research,paper,todo).
priority(tax,conra,todo).
priority(ta,meeting,todo).
