status(osu,admission,todo).
status(osu,life,todo).
status(life,dl,todo).
status(life,apartment,todo).
status(life,books,todo).
status(books,capek,todo).
status(books,dobry,todo).
status(life,movies,todo).
status(movies,czeck_movies,todo).
status(czech_movies,kuky,todo).
status(czech_movies,kolja,todo).
status(czech_movies,wild,todo).
status(life,tax,todo).
status(osu,academics,todo).
status(academics,prilim,todo).
status(academics,quals,todo).
status(academics,cs582,done).
status(academics,cs321,done).
status(academics,cs581,todo).
status(academics,cs533,todo).
status(academics,cs507,todo).
status(academics,research,todo).
status(academics,ta,done).
status(academics,ta,todo).
status(academics,intern,todo).
status(life,ihouse,todo).
status(ihouse,rent,todo).
status(research,paper,todo).
status(tax,conra,todo).
status(ta,meeting,todo).
